### ISSUE TITLE
Strange exception

### ISSUE THREAD

**Issue by nickcodefresh** [bitsofinfo/hazelcast-consul-discovery-spi#13]
Hi,

Whilst running 2 instances of an app we saw this odd exception. Any ideas what taggedAddresses are?

Thanks

Nick

```
flex-mam-app_1       | 2016-08-11 04:20:07 ERROR [flex-mam-app,,,] 1 ---[        cached2]c.h.s.d.integration.DiscoveryService     : [10.9.16.112]:5701 [flex-mam-app] [3.6.3]
 discoverNodes() unexpected error: Consul request failed                                                                                                                     
flex-mam-app_1       | com.orbitz.consul.ConsulException: Consul request failed                                                                                              
flex-mam-app_1       |  at com.orbitz.consul.util.Http.extractConsulResponse(Http.java:49)                                                                                   
flex-mam-app_1       |  at com.orbitz.consul.HealthClient.getHealthyServiceInstances(HealthClient.java:317)                                                                  
flex-mam-app_1       |  at com.orbitz.consul.HealthClient.getHealthyServiceInstances(HealthClient.java:300)                                                                  
flex-mam-app_1       |  at org.bitsofinfo.hazelcast.discovery.consul.ConsulDiscoveryStrategy.discoverNodes(ConsulDiscoveryStrategy.java:185)                                 
flex-mam-app_1       |  at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.discoverNodes(DefaultDiscoveryService.java:74)                                           
flex-mam-app_1       |  at com.hazelcast.cluster.impl.DiscoveryJoiner.getPossibleAddresses(DiscoveryJoiner.java:42)                                                          
flex-mam-app_1       |  at com.hazelcast.cluster.impl.TcpIpJoiner.searchForOtherClusters(TcpIpJoiner.java:501)                                                               
flex-mam-app_1       |  at com.hazelcast.cluster.impl.SplitBrainHandler.searchForOtherClusters(SplitBrainHandler.java:75)                                                    
flex-mam-app_1       |  at com.hazelcast.cluster.impl.SplitBrainHandler.run(SplitBrainHandler.java:42)                                                                       
flex-mam-app_1       |  at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:212)                                      
flex-mam-app_1       |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)                                                                   
flex-mam-app_1       |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)                                                                   
flex-mam-app_1       |  at java.lang.Thread.run(Thread.java:745)                                                                                                             
flex-mam-app_1       |  at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)                                                     
flex-mam-app_1       |  at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)                                                            
flex-mam-app_1       | Caused by: com.orbitz.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class com.orbitz.consul.model.health.ImmutableNo
de] value failed (java.lang.IllegalStateException): Cannot build Node, some of required attributes are not set [taggedAddresses]                                             
flex-mam-app_1       |  at [Source: java.io.InputStreamReader@103f8b67; line: 1, column: 121] (through reference chain: java.util.ArrayList[0]->com.orbitz.consul.model.healt
h.Json["Node"])                                                                                                                                                              
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:262)                                                    
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:445)                    
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:464)                             
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.deser.std.StdValueInstantiator._createUsingDelegate(StdValueInstantiator.java:502)                          
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDelegate(StdValueInstantiator.java:265)                           
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1119)             
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)                                     
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)                                               
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)                                       
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)                                         
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)                                        
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:163)                                         
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:135)                                               
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1119)             
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)                                     
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)                                               
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)                               
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)                               
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)                                
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1578)                                                          
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1183)                                                              
flex-mam-app_1       |  at com.orbitz.retrofit.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)                                  
flex-mam-app_1       |  at com.orbitz.retrofit.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)                                  
flex-mam-app_1       |  at com.orbitz.retrofit.ServiceMethod.toResponse(ServiceMethod.java:117)                                                                              
flex-mam-app_1       |  at com.orbitz.retrofit.OkHttpCall.parseResponse(OkHttpCall.java:211)                                                                                 
flex-mam-app_1       |  at com.orbitz.retrofit.OkHttpCall.execute(OkHttpCall.java:174)                                                                                       
flex-mam-app_1       |  at com.orbitz.consul.util.Http.extractConsulResponse(Http.java:47)                                                                                   
flex-mam-app_1       |  ... 14 common frames omitted                                                                                                                         
flex-mam-app_1       | Caused by: java.lang.IllegalStateException: Cannot build Node, some of required attributes are not set [taggedAddresses]                              
flex-mam-app_1       |  at com.orbitz.consul.model.health.ImmutableNode$Builder.build(ImmutableNode.java:300)                                                                
flex-mam-app_1       |  at com.orbitz.consul.model.health.ImmutableNode.fromJson(ImmutableNode.java:198)                                                                     
flex-mam-app_1       |  at sun.reflect.GeneratedMethodAccessor155.invoke(Unknown Source)                                                                                     
flex-mam-app_1       |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                             
flex-mam-app_1       |  at java.lang.reflect.Method.invoke(Method.java:498)                                                                                                  
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.introspect.AnnotatedMethod.call1(AnnotatedMethod.java:115)                                                  
flex-mam-app_1       |  at com.orbitz.fasterxml.jackson.databind.deser.std.StdValueInstantiator._createUsingDelegate(StdValueInstantiator.java:486)                          
flex-mam-app_1       |  ... 37 common frames omitted    
```

**Comment by nickcodefresh** [comment]
Ah looks like it's an issue with our Consul instance. Hitting http://consul.qa1.ooflex.net:8500/v1/catalog/nodes gives 

```
[

    {
        "Node": "qa1-auth1",
        "Address": "10.20.10.18",
        "TaggedAddresses": {
            null
        },
        "CreateIndex": 2221363,
        "ModifyIndex": 2555309
    },
```

Therefore closing this issue
