### ISSUE TITLE
I am having issues with starting the hazelcast consul discovery

### ISSUE THREAD

**Issue by vigneshsenapathy** [bitsofinfo/hazelcast-consul-discovery-spi#22]
So here is the scenario i am trying.

I have orientdb which uses hazelcast. So i have a hazelcast.xml which looks 

<?xml version="1.0" encoding="UTF-8"?>
<hazelcast id="hazelcast-consul-discovery" 
           xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.6.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <group>
        <name>hazelcast-consul-discovery-spi</name>
        <password>haz3lcast1</password>
    </group>

    <properties>
        <property name="hazelcast.discovery.enabled">true</property>
        <property name="hazelcast.shutdownhook.enabled">false</property>
        <property name="hazelcast.phone.home.enabled">false</property>
        <property name="hazelcast.mancenter.enabled">false</property>
        <property name="hazelcast.memcache.enabled">false</property>
        <property name="hazelcast.rest.enabled">false</property>
        <property name="hazelcast.wait.seconds.before.join">5</property>
        <property name="hazelcast.operation.thread.count">1</property>
        <property name="hazelcast.operation.generic.thread.count">1</property>
        <property name="hazelcast.client.event.thread.count">1</property>
        <property name="hazelcast.event.thread.count">1</property>
        <property name="hazelcast.heartbeat.interval.seconds">5</property>
        <property name="hazelcast.max.no.heartbeat.seconds">30</property>
        <property name="hazelcast.icmp.enabled">true</property>
        <property name="hazelcast.icmp.timeout">5000</property>
        <property name="hazelcast.icmp.ttl">3</property>
        <property name="hazelcast.merge.next.run.delay.seconds">15</property>       
    </properties>

    <network>
        <port auto-increment="true">2434</port>
        
        <join>
            <multicast enabled="false"/>
              <aws enabled="false"/>
              <tcp-ip enabled="false" />
              
             <discovery-strategies>
        
               <discovery-strategy enabled="true"
                   class="org.bitsofinfo.hazelcast.discovery.consul.ConsulDiscoveryStrategy">
        
                 <properties>
                    <property name="consul-host">localhost</property>
                    <property name="consul-port">8500</property>
                    <property name="consul-service-name">hz-discovery-test-cluster</property>
                    <property name="consul-healthy-only">true</property>
                    <property name="consul-discovery-delay-ms">0</property>
                    <property name="consul-ssl-enabled">false</property>
                    <property name="consul-ssl-server-cert-file-path"></property>
                    <property name="consul-ssl-server-cert-base64"></property>
                    <property name="consul-ssl-server-hostname-verify">false</property>
                    <property name="consul-registrator">org.bitsofinfo.hazelcast.discovery.consul.DoNothingRegistrator</property>
                 </properties>
               </discovery-strategy>
             </discovery-strategies>
              
        </join>
    </network>
</hazelcast>

This hazelcast.xml exists in the container and i have a local consul agent running. when i start the container i get the following error:

2017-09-15 19:22:27:345 INFO  [172.17.0.2]:2434 [hazelcast-consul-discovery-spi] [3.7.8] Using ConsulRegistrator: org.bitsofinfo.hazelcast.discovery.consul.DoNothingRegistrator [DiscoveryService]Exception in thread "Thread-0" java.lang.NoClassDefFoundError: com/google/common/net/HostAndPort
	at org.bitsofinfo.hazelcast.discovery.consul.ConsulClientBuilder.buildConsul(ConsulClientBuilder.java:68)
	at org.bitsofinfo.hazelcast.discovery.consul.ConsulDiscoveryStrategy.<init>(ConsulDiscoveryStrategy.java:146)
	at org.bitsofinfo.hazelcast.discovery.consul.ConsulDiscoveryStrategyFactory.newDiscoveryStrategy(ConsulDiscoveryStrategyFactory.java:46)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.buildDiscoveryStrategy(DefaultDiscoveryService.java:217)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:158)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.<init>(DefaultDiscoveryService.java:60)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryServiceProvider.newDiscoveryService(DefaultDiscoveryServiceProvider.java:29)
	at com.hazelcast.instance.Node.createDiscoveryService(Node.java:226)
	at com.hazelcast.instance.Node.<init>(Node.java:193)
	at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:153)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:125)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:176)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:126)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.configureHazelcast(OHazelcastPlugin.java:726)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:154)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1249)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:399)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:46)
Caused by: java.lang.ClassNotFoundException: com.google.common.net.HostAndPort
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more

**Comment by bitsofinfo** [comment]
run maven/gradle dependencies, what does it show?

You should see a block like this. If not something in your build.gradle/pom is excluding the required libs

```
+--- com.orbitz.consul:consul-client:0.13.12
|    +--- com.squareup.retrofit2:retrofit:2.1.0
|    |    \--- com.squareup.okhttp3:okhttp:3.3.0
|    |         \--- com.squareup.okio:okio:1.8.0
|    +--- com.squareup.retrofit2:converter-jackson:2.0.2
|    |    +--- com.squareup.retrofit2:retrofit:2.0.2 -> 2.1.0 (*)
|    |    \--- com.fasterxml.jackson.core:jackson-databind:2.7.2 -> 2.7.4
|    |         +--- com.fasterxml.jackson.core:jackson-annotations:2.7.0 -> 2.7.4
|    |         \--- com.fasterxml.jackson.core:jackson-core:2.7.4
|    +--- com.google.guava:guava:19.0
|    +--- com.google.code.findbugs:jsr305:1.3.9
|    +--- com.fasterxml.jackson.core:jackson-annotations:2.7.4
|    +--- com.fasterxml.jackson.core:jackson-core:2.7.4
|    +--- com.fasterxml.jackson.core:jackson-databind:2.7.4 (*)
|    +--- com.fasterxml.jackson.datatype:jackson-datatype-guava:2.7.4
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.7.4 (*)
|    |    +--- com.fasterxml.jackson.core:jackson-core:2.7.4
|    |    \--- com.google.guava:guava:16.0 -> 19.0
|    +--- org.apache.commons:commons-lang3:3.4
|    \--- org.slf4j:slf4j-api:1.7.21
```

**Comment by vigneshsenapathy** [comment]
@bitsofinfo : it was my issue.. i removed com.google from my assemble which caused the issue

**Comment by pchirumalla** [comment]
vigneshsenapathy , How did you resolve this issue?
