### ISSUE TITLE
unable to connect to consul, NullPointerException

### ISSUE THREAD

**Issue by poblin-orange** [bitsofinfo/hazelcast-consul-discovery-spi#9]
H
ello,
hitting an issue with hazelcast 3.6.2,  see trace below.

My context:
- hazelcast 3.6.2 oss
- jdk 1.8.0
- hazelcast-consul-discovery-spi, 1.0.RC4
- i built an uberjar with hazelcast-consul-discovery-spi, and cfx jax-rs client (as suggested in the README).

Here is my hazelcast.xml discovery snippet

```
...
               <discovery-strategy enabled="true"
                   class="org.bitsofinfo.hazelcast.discovery.consul.ConsulDiscoveryStrategy">

                 <properties>
                       <!--  hostname or IP of the consul server -->
                      <property name="consul-host">localhost</property>

                      <!--  port of the consul server -->
                      <property name="consul-port">8500</property>
...
                      <property name="consul-registrator-config"><![CDATA[
                                                                      {
                                                                        "preferPublicAddress":false,
                                                                        "healthCheckProvider":"org.bitsofinfo.hazelcast.discovery.consul.ScriptHealthCheckBuilder",
                                                                        "healthCheckScript":"exec 6<>/dev/tcp/#MYIP/#MYPORT || (exit 3)",
                                                                        "healthCheckScriptIntervalSeconds":30,
                                                                                                                                                "healthCheckTcp":"ip:port",
                                                                                                                                                "healthCheckTcpIntervalSeconds":30
                                                                      }
                                                                  ]]></property>




```

The exception below happens before connecting to consul (exact same trace with consul up, or down on localhost).

I suspect a classloader issue or incompatibility with cxf 3.0.3 (which is quite old).
Any hint ?
Other jax-rs compatible lib suggestion ?
thx

```
19:57:12.315 [main] INFO  c.h.s.d.integration.DiscoveryService - [192.168.122.1]:5703 [test] [3.6.2] Using ConsulRegistrator: org.bitsofinfo.hazelcast.discovery.consul.LocalDiscoveryNodeRegistrator                                                                                                                                           
19:57:12.315 [main] INFO  c.h.s.d.integration.DiscoveryService - [192.168.122.1]:5703 [test] [3.6.2] Determined local DiscoveryNode address to use: Address[192.168.122.1]:5703                                                                                                                                                                 
19:57:12.453 [main] DEBUG o.apache.cxf.common.logging.LogUtils - Using org.apache.cxf.common.logging.Slf4jLogger for logging.                                           
19:57:12.705 [main] DEBUG o.a.c.jaxrs.provider.ProviderFactory - Problem with creating the default provider org.apache.cxf.jaxrs.provider.json.JSONProvider: org.apache.cxf.jaxrs.provider.json.JSONProvider                                                                                                                                    
19:57:12.715 [main] DEBUG o.a.c.j.model.AbstractResourceInfo - Injecting a custom context org.apache.cxf.jaxrs.ext.MessageContext, ContextProvider is required for this type                                                                                                                                                                    
19:57:12.726 [main] DEBUG o.a.c.j.model.AbstractResourceInfo - Injecting a custom context org.apache.cxf.jaxrs.ext.MessageContext, ContextProvider is required for this type                                                                                                                                                                    
19:57:12.730 [main] DEBUG o.a.c.j.model.AbstractResourceInfo - Injecting a custom context org.apache.cxf.jaxrs.ext.MessageContext, ContextProvider is required for this type                                                                                                                                                                    
19:57:12.732 [main] DEBUG o.a.c.j.model.AbstractResourceInfo - Injecting a custom context org.apache.cxf.jaxrs.ext.MessageContext, ContextProvider is required for this type                                                                                                                                                                    
Apr 27, 2016 7:57:12 PM org.bitsofinfo.hazelcast.discovery.consul.ConsulClientBuilder                                                                                   
SEVERE: Unexpected Error occured while buildConsul() - Error connecting to Consul                                                                                       
com.orbitz.consul.ConsulException: Error connecting to Consul                                                                                                           
        at com.orbitz.consul.AgentClient.ping(AgentClient.java:74)                                                                                                      
        at com.orbitz.consul.Consul.<init>(Consul.java:73)                                                                                                              
        at com.orbitz.consul.Consul.<init>(Consul.java:24)                                                                                                              
        at com.orbitz.consul.Consul$Builder.build(Consul.java:337)                                                                                                      
        at org.bitsofinfo.hazelcast.discovery.consul.ConsulClientBuilder.buildConsul(ConsulClientBuilder.java:71)                                                       
        at org.bitsofinfo.hazelcast.discovery.consul.BaseRegistrator.init(BaseRegistrator.java:96)                                                                      
        at org.bitsofinfo.hazelcast.discovery.consul.ConsulDiscoveryStrategy.<init>(ConsulDiscoveryStrategy.java:122)                                                   
        at org.bitsofinfo.hazelcast.discovery.consul.ConsulDiscoveryStrategyFactory.newDiscoveryStrategy(ConsulDiscoveryStrategyFactory.java:46)                        
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.buildDiscoveryProvider(DefaultDiscoveryService.java:204)                                            
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryProviders(DefaultDiscoveryService.java:145)                                            
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.<init>(DefaultDiscoveryService.java:60)                                                             
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryServiceProvider.newDiscoveryService(DefaultDiscoveryServiceProvider.java:29)                                
        at com.hazelcast.instance.Node.createDiscoveryService(Node.java:217)                                                                                            
        at com.hazelcast.instance.Node.<init>(Node.java:185)                                                                                                            
        at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:125)                                                                          
        at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:160)                                                
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:143)                                                      
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111)                                                      
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)                                                                                         
        at com.hazelcast.core.server.StartServer.main(StartServer.java:36)                                                                                              
Caused by: java.lang.NullPointerException                                                                                                                               
        at org.apache.cxf.jaxrs.client.AbstractClient.setupOutInterceptorChain(AbstractClient.java:847)                                                                 
        at org.apache.cxf.jaxrs.client.AbstractClient.createMessage(AbstractClient.java:924)                                                                            
        at org.apache.cxf.jaxrs.client.WebClient.finalizeMessage(WebClient.java:1109)                                                                                   
        at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1082)                                                                               
        at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:883)                                                                                           
        at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:854)                                                                                           
        at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:417)                                                                                             
        at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.method(WebClient.java:1609)                                                                            
        at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.method(WebClient.java:1604)                                                                            
        at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.get(WebClient.java:1524)                                                                               
        at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.get(InvocationBuilderImpl.java:80)                                                                    
        at com.orbitz.consul.AgentClient.ping(AgentClient.java:66)                                                                                                      
        ... 19 more                                                                                                                                                     

19:57:12.775 [main] ERROR c.h.s.d.integration.DiscoveryService - [192.168.122.1]:5703 [test] [3.6.2] Unexpected error in configuring LocalDiscoveryNodeRegistration: Error connecting to Consul                                                                                                                                                 
com.orbitz.consul.ConsulException: Error connecting to Consul                                                                                                           
        at com.orbitz.consul.AgentClient.ping(AgentClient.java:74) ~[hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                                
        at com.orbitz.consul.Consul.<init>(Consul.java:73) ~[hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                                        
        at com.orbitz.consul.Consul.<init>(Consul.java:24) ~[hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                                        
        at com.orbitz.consul.Consul$Builder.build(Consul.java:337) ~[hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                                
        at org.bitsofinfo.hazelcast.discovery.consul.ConsulClientBuilder.buildConsul(ConsulClientBuilder.java:71) ~[hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                                                                                                                                                         
        at org.bitsofinfo.hazelcast.discovery.consul.BaseRegistrator.init(BaseRegistrator.java:96) ~[hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.bitsofinfo.hazelcast.discovery.consul.ConsulDiscoveryStrategy.<init>(ConsulDiscoveryStrategy.java:122) [hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                                                                                                                                                      
        at org.bitsofinfo.hazelcast.discovery.consul.ConsulDiscoveryStrategyFactory.newDiscoveryStrategy(ConsulDiscoveryStrategyFactory.java:46) [hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                                                                                                                           
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.buildDiscoveryProvider(DefaultDiscoveryService.java:204) [hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                                                                                                                                               
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryProviders(DefaultDiscoveryService.java:145) [hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                                                                                                                                               
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.<init>(DefaultDiscoveryService.java:60) [hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                                                                                                                                                                
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryServiceProvider.newDiscoveryService(DefaultDiscoveryServiceProvider.java:29) [hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                                                                                                                                   
        at com.hazelcast.instance.Node.createDiscoveryService(Node.java:217) [hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                       
        at com.hazelcast.instance.Node.<init>(Node.java:185) [hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                                       
        at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:125) [hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]     
        at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:160) [hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                                                                                                                                                   
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:143) [hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                                                                                                                                                         
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111) [hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                                                                                                                                                         
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58) [hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                    
        at com.hazelcast.core.server.StartServer.main(StartServer.java:36) [hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                         
Caused by: java.lang.NullPointerException: null                                                                                                                         
        at org.apache.cxf.jaxrs.client.AbstractClient.setupOutInterceptorChain(AbstractClient.java:847) ~[hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                                                                                                                                                                   
        at org.apache.cxf.jaxrs.client.AbstractClient.createMessage(AbstractClient.java:924) ~[hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]      
        at org.apache.cxf.jaxrs.client.WebClient.finalizeMessage(WebClient.java:1109) ~[hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]             
        at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1082) ~[hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]         
        at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:883) ~[hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                     
        at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:854) ~[hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                     
        at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:417) ~[hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                       
        at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.method(WebClient.java:1609) ~[hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]      
        at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.method(WebClient.java:1604) ~[hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]      
        at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.get(WebClient.java:1524) ~[hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]         
        at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.get(InvocationBuilderImpl.java:80) ~[hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                                                                                                                                                                      
        at com.orbitz.consul.AgentClient.ping(AgentClient.java:66) ~[hazelcast-bosh-uberjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]                                
        ... 19 common frames omitted                                                                                                                                    
19:57:12.777 [main] ERROR c.h.s.d.integration.DiscoveryService - [192.168.122.1]:5703 [test] [3.6.2] Unexpected error attempting to init() ConsulRegistrator and register(): Unexpected error in configuring LocalDiscoveryNodeRegistration: Error connecting to Consul                                                                         

```

**Comment by poblin-orange** [comment]
I managed to get a running configuration, using jersey jax-rs client.
